### ISSUE TITLE
B9PartSwitch Shows errors while loading

### ISSUE THREAD

**Issue by dsfddsfds** [CobaltWolf/Bluedog-Design-Bureau#912]
Hello! So when I load up KSP I see this: 
![image](https://user-images.githubusercontent.com/33441944/82773651-cbd24d80-9dff-11ea-9819-678d7f166b86.png) And while in game and I use anything at all with bluedog, It shows this: 
![image](https://user-images.githubusercontent.com/33441944/82773804-32576b80-9e00-11ea-8102-fe9ec68ba29a.png) All parts included are Broken/Bugged. I am using the latest verson for 1.8.1. I have never had this issue before. If you need the ksp.log Please tell me.

**Comment by jsolson** [comment]
Yup, we'd need to see a log and GameData/modulemanager.configcache.

**Comment by dsfddsfds** [comment]
Hello! I could not find Modulemanager.configcache, so I just copied all my Module Manager Files over to mega and put them in a folder. Same with KSP.log Here you go. https://mega.nz/folder/KtIHxCwS#14y6ER84m9pA3AzXQEQ1oA

**Comment by jsolson** [comment]
Try [ZeroMiniAVC](https://spacedock.info/mod/1614/ZeroMiniAVC) and see if that fixes it. If it doesn't I'll need to a another log after ZeroMiniAVC is installed. If the ModuleManager errors go away it will generate a ModuleManager.ConfigCache so send that too if possible.

[IMPORTANT Announcement about MiniAVC and ZeroMiniAVC](https://forum.kerbalspaceprogram.com/index.php?/topic/191568-important-announcement-about-miniavc-and-zerominiavc/)

**Comment by dsfddsfds** [comment]
Alright so it still didnt work. ModuleManager is still showing errors. So here is the new one. https://mega.nz/file/n0w2SKgS#c6yl63r7Q9_dy23mYxMqwDU5oP0KOHOD3J2ppBspxDo

**Comment by jsolson** [comment]
You've got a GameData in your GameData now. That's probably where you stuck ZeroMiniAVC. You should fix that.

There's still MiniAVC.dll's floating around. Not sure but the above likely caused it to fail. I'm not certain but you may have to start the game, exit, and start it again for that to do it's thing.

Delete these two files:  `\GameData\ModuleManager.3.0.4.dll` and `\GameData\ModuleManager.4.1.0.dll`

Do all that and if still doesn't work, send yet another log! Sorry for the back and forth, we need to get your ModuleManager working. Hopefully that's all that's wrong.

**Comment by dsfddsfds** [comment]
Hello there, real quick while loading I see this: 
![image](https://user-images.githubusercontent.com/33441944/82857704-048d2800-9ecf-11ea-9c46-a0c317c07507.png) And all the errors went away except a different mod that had a broken part in it.

**Comment by jsolson** [comment]
Kopernicus is version locked, but there's a 1.8.1 version available. Can't help with RSS, sorry.

**Comment by dsfddsfds** [comment]
[KSP.log](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/4679762/KSP.log)
Alright so it is still showing issues. I have deleted the extra Gamedata and put the proper files in, and it still is broken.

**Comment by dsfddsfds** [comment]
I should refraise what i said before, All the module manager errors went away. Not the v9 Partswitch ones.

**Comment by jsolson** [comment]
You'v got this error repeated in the log `Cannot find a PartModule of typename 'ModuleEnginesRF'`. That would imply something is patching for RealFuels, but you don't have RealFuels installed. RO maybe? That would also cause the B9PartSwitch errors.

RO heavily modifies parts from other mods, and may require specific versions of those mods (including this one).

**Comment by dsfddsfds** [comment]
Hello! I have deleted RO and all issues have went away! Thank you for your help and fast replies!
